### ISSUE TITLE
gtf assertion error when installing ensembl release

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/pyensembl#55]
This is on Python 3.

```
$ pyensembl 75 install
INFO:root:Annotation data for release 75 is already downloaded
INFO:root:Transcript sequence data for release 75 is already downloaded
INFO:root:Cached file Homo_sapiens.GRCh37.75.gtf from URL ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz
Creating database: /Users/tim/Library/Caches/ensembl/Homo_sapiens.GRCh37.75.db
INFO:root:Reading GTF /Users/tim/Library/Caches/ensembl/Homo_sapiens.GRCh37.75.gtf into DataFrame
INFO:root:Extracting attributes for 0 entries in GTF DataFrame
INFO:root:Adding attribute columns: []
Traceback (most recent call last):
  File "/Users/tim/sinai/git/datacache/venv/bin/pyensembl", line 9, in <module>
    load_entry_point('pyensembl==0.5.12', 'console_scripts', 'pyensembl')()
  File "/Users/tim/sinai/git/pyensembl/pyensembl/shell.py", line 59, in run
    data.install()
  File "/Users/tim/sinai/git/pyensembl/pyensembl/ensembl_release.py", line 152, in install
    self._index(force=False)
  File "/Users/tim/sinai/git/pyensembl/pyensembl/ensembl_release.py", line 163, in _index
    if self.db.create(force=force):
  File "/Users/tim/sinai/git/pyensembl/pyensembl/database.py", line 515, in create
    self._create_database(force=force)
  File "/Users/tim/sinai/git/pyensembl/pyensembl/database.py", line 153, in _create_database
    df = self.gtf.dataframe()
  File "/Users/tim/sinai/git/pyensembl/pyensembl/gtf.py", line 241, in dataframe
    self._dataframes[key] = cached_dataframe(csv_path, local_loader_fn)
  File "/Users/tim/sinai/git/pyensembl/pyensembl/compute_cache.py", line 92, in cached_dataframe
    df = compute_fn()
  File "/Users/tim/sinai/git/pyensembl/pyensembl/gtf.py", line 215, in local_loader_fn
    full_df = self._load_full_dataframe()
  File "/Users/tim/sinai/git/pyensembl/pyensembl/gtf.py", line 178, in _load_full_dataframe
    return cached_dataframe(csv_path, self._load_full_dataframe_from_gtf)
  File "/Users/tim/sinai/git/pyensembl/pyensembl/compute_cache.py", line 92, in cached_dataframe
    df = compute_fn()
  File "/Users/tim/sinai/git/pyensembl/pyensembl/gtf.py", line 185, in _load_full_dataframe_from_gtf
    return load_gtf_as_dataframe(path)
  File "/Users/tim/sinai/git/pyensembl/pyensembl/gtf_parsing.py", line 309, in load_gtf_as_dataframe
    list(sorted(df.columns)))
AssertionError: Missing required column 'gene_name', available: ['end', 'feature', 'frame', 'score', 'seqname', 'source', 'start', 'strand']

**Comment by iskandr** [comment]
Does this still happen? I wasn't able to recreate it and am not sure if I fixed it previously.

**Comment by timodonnell** [comment]
I think it's fixed. Will reopen if I hit again.
