### ISSUE TITLE
Error while installing because of progressbar...

### ISSUE THREAD

**Issue by alec-djinn** [hammerlab/pyensembl#66]
Here the log..

$ pip3 install pyensembl
Collecting pyensembl
  Downloading pyensembl-0.5.13.tar.gz (51kB)
    100% |################################| 53kB 994kB/s 
    No module named 'pypandoc'
    Failed to convert %s to reStructuredText README.md
Collecting typechecks>=0.0.2 (from pyensembl)
  Downloading typechecks-0.0.2.tar.gz
    [Errno 2] No such file or directory: '/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/typechecks/README.md'
    Failed to open /private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/typechecks/README.md
    No module named 'pypandoc'
    Conversion of long_description from MD to reStructuredText failed
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from pyensembl)
Requirement already satisfied (use --upgrade to upgrade): pandas>=0.13.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from pyensembl)
Collecting datacache>=0.4.11 (from pyensembl)
  Downloading datacache-0.4.13.tar.gz
    WARNING:root:Failed to load README.md
    WARNING:root:Failed to convert README.md to reStructuredText
Collecting pyfaidx>=0.3.4 (from pyensembl)
  Downloading pyfaidx-0.3.8.tar.gz
Collecting memoized-property>=1.0.2 (from pyensembl)
  Using cached memoized-property-1.0.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from pandas>=0.13.1->pyensembl)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from pandas>=0.13.1->pyensembl)
Collecting appdirs>=1.4.0 (from datacache>=0.4.11->pyensembl)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting progressbar>=2.2 (from datacache>=0.4.11->pyensembl)
  Using cached progressbar-2.3.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/progressbar/setup.py", line 5, in <module>
    
        import progressbar
    
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/progressbar/progressbar/__init__.py", line 59, in <module>
    
        from progressbar.widgets import *
    
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/progressbar/progressbar/widgets.py", line 121, in <module>
    
        class FileTransferSpeed(Widget):
    
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/abc.py", line 133, in __new__
    
        cls = super().__new__(mcls, name, bases, namespace)
    
    ValueError: 'format' in __slots__ conflicts with class variable
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-hyavirp_/progressbar

**Comment by iskandr** [comment]
It looks like `progressbar` doesn't work under Python3 due a problem
similar to this one: https://github.com/paramiko/paramiko/issues/103

Which version of Python are you using?

**Comment by alec-djinn** [comment]
Last one, 3.4.2

**Comment by iskandr** [comment]
Should be fixed by a switch from `progressbar` to `progressbar33` in our `datacache` dependency. Can you try upgrading `datacache` and then installing `pyensembl` again?

**Comment by alec-djinn** [comment]
Yes, the issue is solved, now I can pip3 install pyensembl without any problem.
Great!

**Comment by iskandr** [comment]
Awesome!
